### PR TITLE
Release - 0.2.0

### PR DESCRIPTION
**Pull request by hoangnguyen92dn**
## Features

- #3 (@luongvo)
- #6 (@hoangnguyen92dn)
- #7 (@luongvo)
- #10 (@Wadeewee)
- #13 (@Wadeewee)
- #14 (@luongvo)
- #16 (@hoangnguyen92dn)

## Chores

- #35 (@hoangnguyen92dn)

## Bugs

`N/A`

### CODE REVIEW

**Review by Wadeewee — APPROVED** [review]

**Comment by luongvo** [comment]
@hoangnguyen92dn Why do we have some unfinished tasks in release note? Do you intent to wait for include them? 🤔

**Comment by luongvo** [comment]
@hoangnguyen92dn We should not tag a `PR has an issue ticket` to the Project board

image

image

**Comment by hoangnguyen92dn** [comment]
@luongvo I assumed we could finish target tasks for 0.2.0 according the project board. Removed 🚀

**Comment by luongvo** [comment]
@hoangnguyen92dn i still don't see code for app icon update https://github.com/nimblehq/jetpack-compose-crypto/compare/release/0.2.0...develop

**Pull request merged**
